# Generated by Django 5.0 on 2023-12-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Mobile')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_size', models.FloatField()),
                ('processor', models.CharField(max_length=100)),
                ('storage_capacity', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
