# Generated by Django 5.0 on 2023-12-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_mobile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='display_size',
            field=models.CharField(max_length=100),
        ),
    ]
