# Generated by Django 5.0 on 2023-12-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mobile_display_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='storage_capacity',
        ),
    ]
