# Generated by Django 5.0 on 2023-12-13 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mobile_storage_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='internal_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='battery_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='display_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(upload_to='mobile_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
