# Generated by Django 5.0 on 2023-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mobile_is_free_delivary_available_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='ram',
            new_name='RAM',
        ),
        migrations.AddField(
            model_name='mobile',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
