# Generated by Django 5.0 on 2023-12-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ram_mobile_ram_mobile_is_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='image',
            new_name='Img',
        ),
    ]
