# Generated by Django 5.0 on 2023-12-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mobile_img_alter_mobile_phone_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
