# Generated by Django 4.2.6 on 2023-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_brand_brand_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
